import fs from "node:fs"
import path from "node:path"
import YAML from "yaml"
import { VARIANTS, RETIRED, paletteFor } from "./variants.mjs"

const root = path.resolve(import.meta.dirname, "..")
const base = YAML.parseDocument(fs.readFileSync(path.join(root, "quartz.config.yaml"), "utf8"))

function pluginName(source) {
  return source.split("/").at(-1)
}

// Merge a variant's plugin option patch into the plugin's existing options,
// recursing into nested objects so a patch such as { localGraph: { depth: 2 } }
// keeps the other localGraph settings.
function deepMerge(target, patch) {
  for (const [key, value] of Object.entries(patch)) {
    if (value && typeof value === "object" && !Array.isArray(value)) {
      target[key] = deepMerge(target[key] ?? {}, value)
    } else {
      target[key] = value
    }
  }
  return target
}

for (const variant of VARIANTS) {
  const doc = base.clone()
  const cfg = doc.toJS()

  cfg.configuration.theme.typography = variant.fonts
  cfg.configuration.theme.colors = paletteFor(variant.key)

  for (const plugin of cfg.plugins) {
    const name = pluginName(plugin.source)
    const position = variant.positions[name]
    if (position && plugin.layout) plugin.layout.position = position
    if (variant.options?.[name])
      plugin.options = deepMerge(plugin.options ?? {}, variant.options[name])
    // TOC in the header block keeps the same priority ordering after tags.
    if (name === "table-of-contents" && position === "beforeBody") plugin.layout.priority = 40
    if (name === "graph" && position === "afterBody") plugin.layout.priority = 10
    if (name === "backlinks" && position === "afterBody") plugin.layout.priority = 20
  }

  const byPageType = cfg.layout.byPageType
  for (const pageType of ["content", "folder", "tag"]) {
    byPageType[pageType] ??= {}
    if (variant.frame !== "default") byPageType[pageType].template = variant.frame
    else delete byPageType[pageType].template
    const extra = variant.exclude[pageType] ?? []
    if (extra.length) {
      byPageType[pageType].exclude = [
        ...new Set([...(byPageType[pageType].exclude ?? []), ...extra]),
      ]
    }
  }
  // Folder and tag pages keep the right rail empty in production; with graph
  // and backlinks moved under the article they should still show nothing there.
  if (variant.frame !== "default") byPageType["404"].template = variant.frame
  else delete byPageType["404"].template

  const outDir = path.join(root, "variants", variant.key)
  fs.mkdirSync(outDir, { recursive: true })
  const header = `# Generated by variants/make-configs.mjs for design variant "${variant.key}" (${variant.name ?? "retired"}).\n# Do not edit by hand; edit variants/variants.mjs and rerun.\n`
  fs.writeFileSync(path.join(outDir, "quartz.config.yaml"), header + YAML.stringify(cfg))
  console.log(`wrote variants/${variant.key}/quartz.config.yaml`)
}
