// Promote a variant to the production configuration: derive its config from
// the current quartz.config.yaml and write it back, keeping the header comment.
// Usage: node variants/promote.mjs paper-masthead
import fs from "node:fs"
import path from "node:path"
import { spawnSync } from "node:child_process"

const root = path.resolve(import.meta.dirname, "..")
const key = process.argv[2]
if (!key) throw new Error("variant key required")
const generation = spawnSync("node", ["variants/make-configs.mjs"], { cwd: root, stdio: "inherit" })
if (generation.status !== 0) throw new Error("variant config generation failed; nothing promoted")
const generated = fs.readFileSync(path.join(root, "variants", key, "quartz.config.yaml"), "utf8")
const body = generated
  .split("\n")
  .filter((line) => !line.startsWith("# Generated by") && !line.startsWith("# Do not edit by hand"))
  .join("\n")
const current = fs.readFileSync(path.join(root, "quartz.config.yaml"), "utf8")
const header = current
  .split("\n")
  .filter((line, i, all) => all.slice(0, i + 1).every((l) => l.startsWith("#")))
  .filter((line) => !line.startsWith("# Theme: design variant"))
  .join("\n")
fs.writeFileSync(
  path.join(root, "quartz.config.yaml"),
  `${header}\n# Theme: design variant "${key}" promoted to production.\n${body}`,
)
console.log(`quartz.config.yaml now carries variant "${key}"`)
